name: Socket Security Scan

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  socket-security:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: write
      pull-requests: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install Socket CLI
        run: pip install socketsecurity --upgrade

      - name: Determine changed files
        id: changed-files
        run: |
          if [[ "${{ github.event_name }}" == "pull_request" ]]; then
            echo "changed_files=$(git diff --name-only -r HEAD^1 HEAD | xargs)" >> $GITHUB_OUTPUT
          else
            echo "changed_files=$(git diff --name-only ${{ github.event.before }} ${{ github.event.after }} | xargs)" >> $GITHUB_OUTPUT
          fi

      - name: Run Socket Scan
        env:
          SOCKET_SECURITY_API_KEY: ${{ secrets.SOCKET_SECURITY_API_KEY }}
          GH_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          COMMIT_MESSAGE: ${{ github.event.head_commit.message }}
        run: |
          CHANGED_FILES=$(echo "${{ steps.changed-files.outputs.changed_files }}" | tr " " "\n")
          FILES=""
          while IFS= read -r line; do
            FILES="$FILES\"$line\","
          done <<< "$CHANGED_FILES"
          FILES=$(echo $FILES | sed 's/,*$//')
          socketcli --files "[$FILES]" \
            --enable-json \
            --scm github \
            --repo ${{ github.repository }} \
            --branch "${{ github.ref_name }}" \
            --pr_number ${{ github.event.pull_request.number || 0 }} \
            --committer "$GITHUB_ACTOR" \
            --commit_message "$COMMIT_MESSAGE" \
            --target_path $GITHUB_WORKSPACE
